### ISSUE TITLE
replacing random with urandom

### ISSUE THREAD

**Issue by hyperbolicTom** [soulseekah/py-libgfshare#1]

**Comment by soulseekah** [comment]
But we're using the python `random` library and its `sample` method - https://docs.python.org/2/library/random.html#random.sample

The use of `urandom` is completely inappropirate since it may yield non-unique share numbers, so two pieces would be labled with the same share number, which is incorrect. Using `random.sample` we just grab a set of unique share numbers (from 1 to 255 included) in a random order.

The code you pasted might not generate a set of unique share numbers.

``` python
>>> [ord( c ) for c in urandom( 12 )]
[122, 2, 171, 169, 100, 143, 0, 168, 206, 93, 2, 174]
```

Look how 2 is repeated twice, so a same share will be ouptut twice which defeats the purpose of having N unique shares.

Let me know if I'm missing something.

**Comment by hyperbolicTom** [comment]
I know that was a terrible patch, I realized later. Best to shuffle. Never mind.

**Comment by soulseekah** [comment]
Thanks for your input though, Tom :+1 happy to see this being scrutinized and dug into.

**Comment by hyperbolicTom** [comment]
So I decided to use os.urandom, and added randrange and shuffle:

def _fill_random( buffer, count ):
        """fill the buffer with random data."""

```
    s = urandom(count)
    for x in xrange(count):
            buffer[x] = ord(s[x])
```

def randrange(a, b):
        r = b - a
        x = ord(urandom(1))
        return a + ((x - a) % r)

# Create a random permutation by making n - 1 random exchanges. Knuth.

def shuffle(l):
        """shuffle(l) shuffles the list l in place."""
        n = len(l)
        for i in range(n - 1):
                j = randrange(i, n)
                t = l[i]
                l[i] = l[j]
                l[j] = t

then down below;
        # Generate the needed unique share numbers at random
        # 0 shares are NG
        sharenrs = range( 1, 256 )
        shuffle( sharenrs )
        sharenrs = sharenrs[:sharecount]
        sharenrs = list( map( lambda x: c_ubyte( x ), sharenrs ) )
        sharenrs = ( c_ubyte \* len( sharenrs ) )( *sharenrs )

**Comment by soulseekah** [comment]
Why? How does this improve over the current code?

**Comment by hyperbolicTom** [comment]
It uses os.urandom, is all.

I also had a question about libgfshare:
in gfshare_ctx_enc_getshare, there's a line
      share[pos] = *(coefficient_ptr++);
but shouldn't that be *coefficient_ptr++?

Also I changed it to use memset to 0 instead of fill rand when freeing the context. Zero pointers don't cause coredumps when free gets called twice

**Comment by soulseekah** [comment]
So no improvement over the current code, right? I can just ignore your changeset, yes?

As for libgfshare - you should visit https://git.gitano.org.uk/libgfshare.git/ instead this is the python bindings project for it.

`*(ptr++);` is explicit `*ptr++` is not, but they're the same thing. `*ptr++` can be misread by a human as `(*ptr)++`; So use `*(ptr++);` to increment point and then dereference. https://www.eskimo.com/~scs/cclass/notes/sx10b.html

**Comment by hyperbolicTom** [comment]
The parens in *(p++) do nothing! I've been programming in C for over 30 years and never noticed that.
It isn't an issue after all. The (p++) makes me think it increments first, then indirects, but that's wrong. Weird.

**Comment by soulseekah** [comment]
Please contact http://www.digital-scurf.org/software/libgfshare as I haven't been programming in C for over 30 years but he probably has. Thanks.
